### ISSUE TITLE
Deploy script defaults to moloch address instead of execution safe

### ISSUE THREAD

**Issue by dekanbro** [HausDAO/protocol-guild-contracts#2]
https://github.com/HausDAO/protocol-guild-contracts/blob/207fcf5d2399563811c198b1f47124de000f1738/deploy/002_deploy_PGRegistry.ts#L36C79-L36C79

Can probably remove the moloch address because there probably is no reason for it to have ownership

**Comment by santteegt** [comment]
Fixed in [8466a1d](https://github.com/HausDAO/protocol-guild-contracts/commit/8466a1dc5a2d6d1a6f18e6af6979ce4c803f4452)
